### ISSUE TITLE
Null fields are not passed on to Update Requests

### ISSUE THREAD

**Issue by everton-agner** [RallyTools/RallyRestToolkitForJava#22]
The API currently *ignores null fields during serialization*, therefore it's not possible to clear up an entity field by setting it as null.

This issue was confirmed by a support case on Rally Community (**#816821**)

**Comment by everton-agner** [comment]
I've put together a Pull Request to provide the ability to customize a GsonBuilder instance used for serialization, making it possible to enable the **serializeNulls** option and many other options.

See https://github.com/RallyTools/RallyRestToolkitForJava/pull/21

**Comment by krmorse** [comment]
Fixed in release 2.1.2

**Comment by krmorse** [comment]
In addition to supporting the ability to set a GsonBuilder instance on a request we also made it serialize nulls by default since this seems like a very common scenario.
