### ISSUE TITLE
Information on how to generate API Key

### ISSUE THREAD

**Issue by rmohta** [RallyTools/RallyRestToolkitForJava#23]
It would be great of user guide have a section on how to generate API Key. It's very simple, but this information is not easily available. 

I was able to generate after [reading this SO answer](http://stackoverflow.com/a/27390012/1843067)

**Comment by krmorse** [comment]
I agree.  I'll try to get the docs update soon...

**Comment by krmorse** [comment]
I added a link to the help docs in the user guide here: https://github.com/RallyTools/RallyRestToolkitForJava/wiki/User-Guide#usage
