### ISSUE TITLE
updateCollection does not work

### ISSUE THREAD

**Issue by mengbinhao** [RallyTools/RallyRestToolkitForJava#28]
Hi there, 
Below is my code snippet,  it met error after I ran it.
error: Caused by: java.io.IOException: HTTP/1.1 405 Could not find web service for /project/28909928070/remove.js¼ using request method POST¼.  However a service does exist at that path using method(s) GET¼.

I did some research, because the first invoke Rally api ( restApi.query) use doGet request for querying defects, but updateCollection use doPost request. I have to get some defects first, then batch update them, How do I use updateCollection?

`    RallyRestApi restApi = null;
    try
    {
      restApi = new RallyRestApi(new URI("https://rally1.rallydev.com"), apiKey);
      
QueryRequest defectRequest = new QueryRequest("defect");
      defectRequest.setWorkspace("/workspace/xxxx");
      defectRequest.setProject("/project/xxxx");
      defectRequest.setFetch(new Fetch("FormattedID", "Name"));
      defectRequest.setQueryFilter(new QueryFilter("State", "=", "Open"));
      QueryResponse queryResponse = restApi.query(defectRequest);
      JsonArray items = queryResponse.getResults();
      String collectionRef = "/defect?project=https://rally1.rallydev.com/slm/webservice/v2.0/project/xxxxxx";
      CollectionUpdateRequest defectTCollectionAddRequest = new CollectionUpdateRequest(collectionRef, items, false);
      CollectionUpdateResponse defectTagCollectionAddResponse = restApi.updateCollection(defectTCollectionAddRequest);
      System.out.println(defectTagCollectionAddResponse.getResults());
      restApi.close();
    }
    catch (Exception e)
    {
      try
      {
        if (restApi != null)
        {
          restApi.close();
        }
      }
      catch (IOException e1)
      {
        e1.printStackTrace();
      }
    }`

**Comment by mengbinhao** [comment]
updateCollection  just add or remove items

**Comment by mengbinhao** [comment]
but same error when I add new items (like defect)

**Comment by krmorse** [comment]
The updateCollection methods are for modifying collections- something like adding tags to a defect or adding defects to a story.  Is that what you're trying to do here?  Otherwise there is currently no way to batch update individual defect objects in one request using the java toolkit.

**Comment by mengbinhao** [comment]
Hi  krmorse,  Thank you for your response. I do want to  batch update some individual defects. but some defects have story,  the rest may not  have story, if updateCollection methods can add defects to a story. How do I accomplish it?

I code a sample for test,  query some defect first, then updateCollection as below,  but same error as yeserday.  Is the collectionRef variable incorrect?

String collectionRef = "/hierarchicalrequirement?project=https://rally1.rallydev.com/slm/webservice/v2.0/project/xxxxx";
          
CollectionUpdateRequest defectTCollectionAddRequest = new CollectionUpdateRequest(collectionRef, queryResponse.getResults(), true);
      CollectionUpdateResponse defectTagCollectionAddResponse = restApi.updateCollection(defectTCollectionAddRequest);`

**Comment by krmorse** [comment]
Correct, that is not a valid collection ref.  What exactly are you trying to do?  Are you trying to add a bunch of defects to a story?  If so, then the collectionRef should be "/hierarchicalrequirement/12345/defects"...

**Comment by mengbinhao** [comment]
gotcha! Thanks you.
