### ISSUE TITLE
NullPointerException during parseArray for getErrors

### ISSUE THREAD

**Issue by pradeagr** [RallyTools/RallyRestToolkitForJava#29]
Doing a query on hierarchicalrequirement/\<objectid\> (for a user story) and getting below exception:

Exception in thread "main" java.lang.NullPointerException
	at com.rallydev.rest.response.Response.parseArray(Response.java:64)
	at com.rallydev.rest.response.Response.getErrors(Response.java:43)
	at com.rallydev.rest.response.Response.wasSuccessful(Response.java:34)
	at com.rallydev.rest.RallyRestApi.query(RallyRestApi.java:173)

Note:
1. Accessing same url in browser is giving required data.
2. Querying for hierarchicalrequirement/\<objectid\>/children is successful using the api.

**Comment by krmorse** [comment]
Hmm, that's pretty weird.  Could you share a bit more of your code?  This toolkit sees a lot of monthly usage and I haven't heard any other reports of this.  You aren't passing compact=true as query string parameter are you?  Because that is not currently supported...

**Comment by pradeagr** [comment]
Here is the code that I am using:

RallyRestApi restApi = new RallyRestApi(new URI("https://rally1.rallydev.com/"), "_myApiKey");
restApi.setApplicationName("Audit");
String url = "hierarchicalrequirement/" + userStoryObjId;   //userStoryObjId is something that is passed to method
QueryRequest rallyUserStory = new QueryRequest(url);
rallyUserStory.setQueryFilter(new QueryFilter("FormattedID", "=", userStoryId));  //userStoryId is passed to function
QueryResponse queryResponse = restApi.query(rallyUserStory);

Also, when I access same url using browser, I am getting correct data.

I am not using compact=true.

**Comment by krmorse** [comment]
If you have the objectid of the story then you can just use the [get](https://github.com/RallyTools/RallyRestToolkitForJava/wiki/User-Guide#get) method instead.  QueryRequest expects just a type or a collection to load, not an individual object.
