### ISSUE TITLE
Rally integration with Jenkin pipeline

### ISSUE THREAD

**Issue by chethanbs** [RallyTools/RallyRestToolkitForJava#33]
Hi Team,

I am using groovy for creating builds and doing deployment in jenkin pipeline.

I have a requirement to integrate Rally with pipeline job.
Could you please let me know the groovy scripts or any idea how do I integrate Rally with pipeline job using groovy scripts?

**Comment by krmorse** [comment]
I'm not super familiar with groovy or jenkins, but as long as you can use java libraries it should be straightforward.  Check out the user guide to get started.  
https://github.com/RallyTools/RallyRestToolkitForJava/wiki/User-Guide

Especially the examples at the bottom.
